baseURL = 'https://brysbroughton.com/'
languageCode = 'en-us'
title = 'Brys Broughton | Software Engineer'
theme = "devresume"
publishdir = 'docs'
googleAnalytics = 'UA-59921787-1'




[params]
    author = "brysbroughton"
    description = "Resume and contact information for Brys Broughton, Software Engineer"
    keywords = "keywords"


    primaryColor = "#355E3B"
    textPrimaryColor = "#303030"




    [params.profile]
        enable = true
        name = "Brys Broughton"
        tagline = "Senior Software Engineer"
        avatar = "brys-broughton-headshot.jpg"







    [params.contact]
        enable = true
        location = "Washington D.C."

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:417-459-2742"
        text = "417-459-2742"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:brysbroughton@gmail.com"
        text = "brysbroughton@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://brysbroughton.com"
        text = "brysbroughton.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "C# .Net"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "JavaScript, Vue.js"
        [[params.skills.list.items]]
        details = "T-SQL/MySQL"
        [[params.skills.list.items]]
        details = "WordPress, OpenText WSM"
        [[params.skills.list.items]]
        details = "DevOps and CI/CD"
        [[params.skills.list.items]]
        details = "Accessible application development"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Full-stack development"
        [[params.skills.list.items]]
        details = "Enterprise website management"
        [[params.skills.list.items]]
        details = "Agile project management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Graduate Certificate in Data Science"
        university = "University of Maryland, College Park"
        dates = "2019 - 2020"
        [[params.education.list]]
        degree = "Bachelor of Science in Computer Science"
        university = "Missouri State University"
        dates = "2009 - 2014"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Hiking, Running"
        [[params.interests.list]]
        name = "Board Games"
        [[params.interests.list]]
        name = "Spanish literature"
        [[params.interests.list]]
        name = "Volunteer at Meals on Wheels"








    [params.summary]
        enable = true
        text = "I specialize in full-stack application development and websites for large enterprises. With 10 years' experience delivering applications in the web services space, I am looking to branch out to new challenges in cloud and analytics applications. Currently obsessed with automating all the things in DevOps and CI/CD and looking forward to hearing about your project."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Developer III"
        dates = "2016/05 – Present"
        company = "Federal Reserve Board of Governors"
        details = "Develops software solutions for enterprise web applications, internal process automation, and web content management. Optimizes new and existing software for performance, security and accessibility. Key technologies: C# .Net, .Net Core, Vue.js, Bootstrap, T-SQL, Azure DevOps CI/CD, WebAPI, REST, OpenText CMS (WSMS), Git "
        [[params.experience.list.items]]
        details = "Lead architecture and development of time-sensitive publishing system, securing the embargoed release of sensitive publications"
        [[params.experience.list.items]]
        details = "Lead architecture and development of configurable workflow automation system for critical publishing, streamlining inter-department transmission and oversite"
        [[params.experience.list.items]]
        details = "Managed the development and execution of 5000+ web page migration project"
        [[params.experience.list.items]]
        details = "Designed extensible service-oriented architecture for long running CMS batch jobs"
        

        [[params.experience.list]]
        title = "Accessibility Analyst"
        dates = "2016/01 – 2016/05"
        company = "Level Access"
        details = "Analyzed websites and applications to ensure equal accessibility for users of all abilities. Provided remedial code samples to bridge any gaps in accessibility. Tested with assistive software to ensure access. Key technologies: JavaScript, HTML, CSS, JAWS, NVDA, VoiceOver, TalkBack"
        [[params.experience.list.items]]
        details = "Remediated 30+ websites, desktop and mobile applications"
        [[params.experience.list.items]]
        details = "Automated 508, WCAG compliance reporting tasks with JavaScript macros"

        [[params.experience.list]]
        title = "Full-Stack Developer"
        dates = "2015/09 – 2016/01"
        company = "E.J. Caimen"
        details = "Enabled business analysts to track production processes through the development of new consolidated reporting dashboards. Key technologies: ASP.Net Framework, C#, MVC, Entity Framework (EF), T-SQL, JavaScript, jQuery, Bootstrap, Jira, Team Foundation Server"
        [[params.experience.list.items]]
        details = "Delivered consolidated web UI with window into disparate KPI’s"
        [[params.experience.list.items]]
        details = "Delivered working increments with unit tests according to Agile Scrum and TDD"

        [[params.experience.list]]
        title = "Coordinator of Web Services"
        dates = "2014/06 – 2015/08"
        company = "Ozarks Technical Community College"
        details = "Oversaw new website and feature requests, research and development of new technologies, and the maintenance of existing systems. Coordinated multiple concurrent projects, managed student developers, and met competing deadlines. Key technologies: PHP, Apache, IIS, JavaScript, jQuery, REST, OAuth, RedDot/OpenText WSM, WordPress, Git, Asana, SOAP, Python, Bash, Google Mini, Open Graph (OG) microdata, MySQL, C# .Net"
        [[params.experience.list.items]]
        details = "Administered enterprise public website, CMS of 7500+ pages"
        [[params.experience.list.items]]
        details = "Coordinated all incoming site/feature requests, end-user training, and support on campus"
        [[params.experience.list.items]]
        details = "Optimized website for accessibility, speed, search engine ranking (SEO)"
        [[params.experience.list.items]]
        details = "Trained and managed small team of student developers in Agile SDLC (Scrum) and special projects"

        [[params.experience.list]]
        title = "Web Developer"
        dates = "2012/07 – 2014/06"
        company = "Missouri State University office of web and new media"
        details = "Developed new websites and web application for university programs and departments. Implemented website redesigns. Maintained databases and database-driven applications. Key technologies: ASP.Net, C#, Web Forms, T-SQL, JavaScript, jQuery, Google Closure, OAuth, IIS"
        [[params.experience.list.items]]
        details = "Implemented 25+ site redesigns"
        [[params.experience.list.items]]
        details = "Delivered reusable Flickr slideshow CMS module"


    [params.custom]
        enable = true
        title="Custom section"







    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/brysbroughton"
        title = "brysbroughton"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/brysbroughton"
        title = "brysbroughton"
        # [[params.social.list]]
        # icon = "fab fa-twitter-square"
        # url = "//twitter.com/username"
        # title = "@username"





